import React, { FC } from 'react'

type SmallProps = {
  small?: string
  autoGeneratedLinkDeps?: Record<string, string>
}

const Small: FC<SmallProps> = (props): JSX.Element => {
  const { small, autoGeneratedLinkDeps } = props

  if (small) return <small className="form-text text-muted">{small}</small>
  if (autoGeneratedLinkDeps?.name === 'video.url') {
    return (
      <small className="form-text text-muted">
        Check autogenerated link:
        <small className="form-text text-muted">
          <a href={autoGeneratedLinkDeps?.previewLink} target="_blank" rel="noreferrer">
            {autoGeneratedLinkDeps?.previewLink}
          </a>
        </small>
      </small>
    )
  }

  return <></>
}

export default Small
