export const ADD_VIDEO_CONTENT = 'ADD_VIDEO_CONTENT'
export const REMOVE_VIDEO_CONTENT = 'REMOVE_VIDEO_CONTENT'

export const ADD_AUDIO_CONTENT = 'ADD_AUDIO_CONTENT'
export const REMOVE_AUDIO_CONTENT = 'REMOVE_AUDIO_CONTENT'

export const ADD_TEXT_CONTENT = 'ADD_TEXT_CONTENT'
export const REMOVE_TEXT_CONTENT = 'REMOVE_TEXT_CONTENT'

export const CLEAR_ENTIRE_CONTENT = 'CLEAR_ENTIRE_CONTENT'
