export const GET_VIDEO_LIST = {
  START: 'GET_VIDEO_LIST/START',
  SUCCESS: 'GET_VIDEO_LIST/SUCCESS',
  FAIL: 'GET_VIDEO_LIST/FAIL',
}

export const GET_VIDEO = {
  START: 'GET_VIDEO/START',
  SUCCESS: 'GET_VIDEO/SUCCESS',
  FAIL: 'GET_VIDEO/FAIL',
}
export const GET_PREVIEW_LINK = {
  START: 'GET_PREVIEW_LINK/START',
  SUCCESS: 'GET_PREVIEW_LINK/SUCCESS',
  FAIL: 'GET_PREVIEW_LINK/FAIL',
}

export const ADD_VIDEO = {
  START: 'ADD_VIDEO/START',
  SUCCESS: 'ADD_VIDEO/SUCCESS',
  FAIL: 'ADD_VIDEO/FAIL',
}
export const UPDATE_VIDEO = {
  START: 'UPDATE_VIDEO/START',
  SUCCESS: 'UPDATE_VIDEO/SUCCESS',
  FAIL: 'UPDATE_VIDEO/FAIL',
}
export const REMOVE_VIDEO = {
  START: 'REMOVE_VIDEO/START',
  SUCCESS: 'REMOVE_VIDEO/SUCCESS',
  FAIL: 'REMOVE_VIDEO/FAIL',
}

export const SET_VIDEO = 'SET_VIDEO'
