name: BUILD_ON_PUSH

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: rm -rf build
      - run: npm install
      - run: npm run-script build --if-present
      - run: cp -r build/* build/index.html build/robots.txt build/asset-manifest.json /var/www/contentpedia.ru
      # - run: npm run-script test --if-present
