name: PUBLISH_ON_PUSH

on:
  push:
    branch: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create build
        run: rm -rf build
          yarn install
          yarn build

  build_and_pub:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Connecting via SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # port: ${{ secrets.CONTENTPEDIA.PORT }}
          key: ${{secrets.SSH_PRIVATE}}
          fingerprint: ${{secrets.SSH_KEY}}
          script: cd ../var/www/contentpedia.ru/
            git clone git@github.com:moiskillnadne/contentpedia_dev_react.git
            cd contentpedia_dev_react/
            npm install
            npm run-script build
            cp -R build/* build/asset-manifest.json build/index.html build/robots.txt ../contentpedia.ru/
            nginx -s reload
            cd ../
            rm -rf contentpedia_dev_react/
